### ISSUE TITLE
Dependency Tunnel Description

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#92]
Elaborate on the description:

https://github.com/tsaad-dev/te/blob/d0e72634093790af8bd685fa87f4c4418297f98e/ietf-te.yang#L832

**Comment by sergiobelotti** [comment]
A first text proposal:
"The “dependency-tunnel” , is a list of tunnels, not yet instantiated, that the client can indicate  to the server controller as “potentially” used for the path computation of a tunnel, so that path computation can use these tunnels as were already setup . 
As soon as server controller instantiates one of these tunnels indicated by dependency tunnel, a related hierarchical link is created in the client topology"

**Comment by italobusi** [comment]
**2020-04-07 Italo/Sergio**

This is the definition we have proposed for the TE tutorial (https://github.com/tsaad-dev/te/issues/48#issuecomment-610492307):

> o	Dependency TE tunnel - a hierarchical TE tunnel provisioned or to be provisioned in an immediately adjacent server layer a given client layer TE tunnel depends on for multi layer path computation. A dependency TE tunnel is provisioned if and only if it is used (selected by path computation) at least by one client layer TE tunnel. The TE link in the client layer network topology supported by a dependence TE tunnel is dynamically created only when the dependency TE tunnel is actually provisioned.

It may be worthwhile moving it to the TE tunnel draft and referencing it from the TE Tutorial

@tsaad-dev : what do you think?

**Comment by tsaad-dev** [comment]
Accepted. This has been added in the ID of the TE module and will show up in next revision
